const currencies = [
  { ticker: 'AED', image: '/images/AED.png' },
  { ticker: 'ARS', image: '/images/ARS.png' },
  { ticker: 'AUD', image: '/images/AUD.png' },
  { ticker: 'BAT', image: '/images/BAT.png' },
  { ticker: 'BCH', image: '/images/BCH.png' },
  { ticker: 'BRL', image: '/images/BRL.png' },
  { ticker: 'BTC', image: '/images/BTC.png' },
  { ticker: 'BTG', image: '/images/BTG.png' },
  { ticker: 'CAD', image: '/images/CAD.png' },
  { ticker: 'CHF', image: '/images/CHF.png' },
  { ticker: 'CNY', image: '/images/CNY.png' },
  { ticker: 'DASH', image: '/images/DASH.png' },
  { ticker: 'DKK', image: '/images/DKK.png' },
  { ticker: 'ETH', image: '/images/ETH.png' },
  { ticker: 'EUR', image: '/images/EUR.png' },
  { ticker: 'GBP', image: '/images/GBP.png' },
  { ticker: 'HKD', image: '/images/HKD.png' },
  { ticker: 'ILS', image: '/images/ILS.png' },
  { ticker: 'INR', image: '/images/INR.png' },
  { ticker: 'JPY', image: '/images/JPY.png' },
  { ticker: 'KES', image: '/images/KES.png' },
  { ticker: 'LTC', image: '/images/LTC.png' },
  { ticker: 'MXN', image: '/images/MXN.png' },
  { ticker: 'NOK', image: '/images/NOK.png' },
  { ticker: 'NZD', image: '/images/NZD.png' },
  { ticker: 'PHP', image: '/images/PHP.png' },
  { ticker: 'PLN', image: '/images/PLN.png' },
  { ticker: 'RVR', image: '/images/RVR.png' },
  { ticker: 'SEK', image: '/images/SEK.png' },
  { ticker: 'SGD', image: '/images/SGD.png' },
  { ticker: 'UAE', image: '/images/UAE.png' },
  { ticker: 'USD', image: '/images/USD.png' },
  { ticker: 'VOX', image: '/images/VOX.png' },
  { ticker: 'XAG', image: '/images/XAG.png' },
  { ticker: 'XAU', image: '/images/XAU.png' },
  { ticker: 'XPD', image: '/images/XPD.png' },
  { ticker: 'XPT', image: '/images/XPT.png' },
  { ticker: 'XRP', image: '/images/XRP.png' },
];

export default currencies;
